import type { Metadata } from 'next'
import { Inter, Outfit } from 'next/font/google'
import '@repo/ui/styles.css'
import { Providers } from '@/client/providers'
import { Toaster } from '@repo/ui/components/sonner'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const outfit = Outfit({ subsets: ['latin'], variable: '--font-outfit' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}${outfit.variable} antialiased`}>
        <Providers>
          <Toaster richColors />
          {children}
        </Providers>
      </body>
    </html>
  )
}
